services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    env_file:
      - .env
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gp-shared-net

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6380:6379"
    restart: always
    networks:
      - gp-shared-net

  phpmyadmin:
#    image: arm64v8/phpmyadmin # only for macbook
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
#    platform: linux/arm64 # only for macbook
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - gp-shared-net

volumes:
  mysql_data:

networks:
  gp-shared-net:
    external: true
